// <auto-generated />
using System;
using BlazorMedical.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BlazorMedical.Data.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20210407032501_creacionDatos")]
    partial class creacionDatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BlazorMedical.Data.Entities.Especialidad", b =>
                {
                    b.Property<string>("EspecialidadId")
                        .HasColumnType("text")
                        .HasColumnName("especialidadId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("EspecialidadId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Medico", b =>
                {
                    b.Property<string>("MedicoId")
                        .HasColumnType("text")
                        .HasColumnName("medicoId");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Apellido2")
                        .HasColumnType("text")
                        .HasColumnName("apellido2");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuit");

                    b.Property<string>("DireccionCalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionCalle");

                    b.Property<string>("DireccionCp")
                        .HasColumnType("text")
                        .HasColumnName("direccionCp");

                    b.Property<string>("DireccionLocalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionLocalidad");

                    b.Property<string>("DireccionNumero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionNumero");

                    b.Property<string>("DireccionPais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionPais");

                    b.Property<string>("DireccionProvinciaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionProvinciaId");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaDeNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Nombre2")
                        .HasColumnType("text")
                        .HasColumnName("nombre2");

                    b.Property<string>("PaisNacimientoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paisNacimientoId");

                    b.HasKey("MedicoId");

                    b.HasIndex("DireccionProvinciaId");

                    b.HasIndex("PaisNacimientoId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.MedicoEspecialidad", b =>
                {
                    b.Property<string>("MedicoEspecialidadId")
                        .HasColumnType("text")
                        .HasColumnName("medicoEspecialidadId");

                    b.Property<string>("EspecialidadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EspecialidadId");

                    b.Property<string>("MedicoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medicoId");

                    b.HasKey("MedicoEspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("MedicoId");

                    b.ToTable("MedicoEspecialidades");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Paciente", b =>
                {
                    b.Property<string>("PacienteId")
                        .HasColumnType("text")
                        .HasColumnName("pacienteId");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Apellido2")
                        .HasColumnType("text")
                        .HasColumnName("apellido2");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuit");

                    b.Property<string>("DireccionCalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionCalle");

                    b.Property<string>("DireccionCp")
                        .HasColumnType("text")
                        .HasColumnName("direccionCp");

                    b.Property<string>("DireccionLocalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionLocalidad");

                    b.Property<string>("DireccionNumero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionNumero");

                    b.Property<string>("DireccionPais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionPais");

                    b.Property<string>("DireccionProvinciaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccionProvinciaId");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaDeNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Nombre2")
                        .HasColumnType("text")
                        .HasColumnName("nombre2");

                    b.Property<string>("PaisNacimientoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paisNacimientoId");

                    b.HasKey("PacienteId");

                    b.HasIndex("DireccionProvinciaId");

                    b.HasIndex("PaisNacimientoId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Pais", b =>
                {
                    b.Property<string>("PaisId")
                        .HasColumnType("text")
                        .HasColumnName("paisId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            PaisId = "0784a240-0207-4197-844f-b27bad955ca007/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            PaisId = "b9136ed7-32f6-46c3-8d8a-771084733e6207/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            PaisId = "2b3a9bf3-5d2a-4c05-b1e1-645c3b47ba7c07/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            PaisId = "ba4abba2-ff03-4c6e-b796-fea6b1d4d13307/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Paraguay"
                        },
                        new
                        {
                            PaisId = "a9ea628b-a86c-4fc0-8100-69fd61c9194507/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Chile"
                        },
                        new
                        {
                            PaisId = "688fd2b4-0817-4f6f-b00a-1a37703710ca07/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Bolivia"
                        });
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Provincia", b =>
                {
                    b.Property<string>("ProvinciaId")
                        .HasColumnType("text")
                        .HasColumnName("provinciaId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("ProvinciaId");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            ProvinciaId = "fa86f43c-114c-4c9e-b0d8-3a881d66c5f907/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            ProvinciaId = "2cf0e11b-b13d-4f4a-9401-6e025970f8b307/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "C.A.B.A"
                        },
                        new
                        {
                            ProvinciaId = "3ded5533-0800-47bb-b6b2-7261af3c5dbb07/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            ProvinciaId = "b5ab28ef-6828-4a67-93df-e9fe6605d68d07/04/2021 0:25:01",
                            Descripcion = "",
                            Nombre = "Entre Rios"
                        });
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Medico", b =>
                {
                    b.HasOne("BlazorMedical.Data.Entities.Provincia", "DireccionProvincia")
                        .WithMany("Medicos")
                        .HasForeignKey("DireccionProvinciaId")
                        .HasConstraintName("FK_Medicos_Provincias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMedical.Data.Entities.Pais", "PaisNacimiento")
                        .WithMany("Medicos")
                        .HasForeignKey("PaisNacimientoId")
                        .HasConstraintName("FK_Medicos_Paises")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DireccionProvincia");

                    b.Navigation("PaisNacimiento");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.MedicoEspecialidad", b =>
                {
                    b.HasOne("BlazorMedical.Data.Entities.Especialidad", "Especialidad")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .HasConstraintName("FK_MedicoEspecialidades_Especialidades")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMedical.Data.Entities.Medico", "Medico")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("MedicoId")
                        .HasConstraintName("FK_MedicoEspecialidades_Medico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Paciente", b =>
                {
                    b.HasOne("BlazorMedical.Data.Entities.Provincia", "DireccionProvincia")
                        .WithMany("Pacientes")
                        .HasForeignKey("DireccionProvinciaId")
                        .HasConstraintName("FK_Pacientes_Provincias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMedical.Data.Entities.Pais", "PaisNacimiento")
                        .WithMany("Pacientes")
                        .HasForeignKey("PaisNacimientoId")
                        .HasConstraintName("FK_Pacientes_Paises")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DireccionProvincia");

                    b.Navigation("PaisNacimiento");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Especialidad", b =>
                {
                    b.Navigation("MedicoEspecialidades");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Medico", b =>
                {
                    b.Navigation("MedicoEspecialidades");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Pais", b =>
                {
                    b.Navigation("Medicos");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("BlazorMedical.Data.Entities.Provincia", b =>
                {
                    b.Navigation("Medicos");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
